name: "kali linux docker CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 * * 0' #At 00:00 on Sunday every week    

jobs:

  #deprecated
  ubuntu-1604-job:
    name: "kali on ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls


  ubuntu-1804-job:
    name: "kali onubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls


  ubuntu-2004-job:
    name: "kali on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls

  ubuntu-latest-job:
    name: "kali on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls