name: "ubuntu kali linux docker CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  ubuntu-1604-job:
    name: "osquery on ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls
        docker run --name kaliroll01 --rm -i -t kalilinux/kali-rolling bash
        sleep 5
        docker container ls
        docker ps -a

  ubuntu-1804-job:
    name: "osquery onubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls
        docker run --name kaliroll01 --rm -i -t kalilinux/kali-rolling bash
        sleep 5
        docker container ls
        docker ps -a

  ubuntu-2004-job:
    name: "osquery on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "docker kalilinux/kali-rolling"
      run: |
        docker pull  kalilinux/kali-rolling 
        docker image ls
        docker run --name kaliroll01 --rm -i -t kalilinux/kali-rolling bash
        sleep 5
        docker container ls
        docker ps -a
